// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: URS_Wearable.proto

package com.tutorial.protobuf;

public final class URS_WearableProto {
  private URS_WearableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface drone_idOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 uav_id = 1;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    boolean hasUavId();
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    int getUavId();
  }
  /**
   * Protobuf type {@code drone_id}
   */
  public static final class drone_id extends
      com.google.protobuf.GeneratedMessage
      implements drone_idOrBuilder {
    // Use drone_id.newBuilder() to construct.
    private drone_id(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private drone_id(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final drone_id defaultInstance;
    public static drone_id getDefaultInstance() {
      return defaultInstance;
    }

    public drone_id getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private drone_id(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uavId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_drone_id_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_drone_id_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.URS_WearableProto.drone_id.class, com.tutorial.protobuf.URS_WearableProto.drone_id.Builder.class);
    }

    public static com.google.protobuf.Parser<drone_id> PARSER =
        new com.google.protobuf.AbstractParser<drone_id>() {
      public drone_id parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new drone_id(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<drone_id> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 uav_id = 1;
    public static final int UAV_ID_FIELD_NUMBER = 1;
    private int uavId_;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public boolean hasUavId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public int getUavId() {
      return uavId_;
    }

    private void initFields() {
      uavId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uavId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uavId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.drone_id parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tutorial.protobuf.URS_WearableProto.drone_id prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drone_id}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tutorial.protobuf.URS_WearableProto.drone_idOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_drone_id_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_drone_id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.URS_WearableProto.drone_id.class, com.tutorial.protobuf.URS_WearableProto.drone_id.Builder.class);
      }

      // Construct using com.tutorial.protobuf.URS_WearableProto.drone_id.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uavId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_drone_id_descriptor;
      }

      public com.tutorial.protobuf.URS_WearableProto.drone_id getDefaultInstanceForType() {
        return com.tutorial.protobuf.URS_WearableProto.drone_id.getDefaultInstance();
      }

      public com.tutorial.protobuf.URS_WearableProto.drone_id build() {
        com.tutorial.protobuf.URS_WearableProto.drone_id result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.URS_WearableProto.drone_id buildPartial() {
        com.tutorial.protobuf.URS_WearableProto.drone_id result = new com.tutorial.protobuf.URS_WearableProto.drone_id(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uavId_ = uavId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.URS_WearableProto.drone_id) {
          return mergeFrom((com.tutorial.protobuf.URS_WearableProto.drone_id)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.URS_WearableProto.drone_id other) {
        if (other == com.tutorial.protobuf.URS_WearableProto.drone_id.getDefaultInstance()) return this;
        if (other.hasUavId()) {
          setUavId(other.getUavId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.URS_WearableProto.drone_id parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.URS_WearableProto.drone_id) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 uav_id = 1;
      private int uavId_ ;
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public boolean hasUavId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public int getUavId() {
        return uavId_;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder setUavId(int value) {
        bitField0_ |= 0x00000001;
        uavId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder clearUavId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uavId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:drone_id)
    }

    static {
      defaultInstance = new drone_id(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:drone_id)
  }

  public interface GotoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 uav_id = 1;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    boolean hasUavId();
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    int getUavId();

    // optional double x = 2;
    /**
     * <code>optional double x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 2;</code>
     */
    double getX();

    // optional double y = 3;
    /**
     * <code>optional double y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 3;</code>
     */
    double getY();

    // optional double z = 4;
    /**
     * <code>optional double z = 4;</code>
     */
    boolean hasZ();
    /**
     * <code>optional double z = 4;</code>
     */
    double getZ();

    // optional double yaw = 5;
    /**
     * <code>optional double yaw = 5;</code>
     */
    boolean hasYaw();
    /**
     * <code>optional double yaw = 5;</code>
     */
    double getYaw();
  }
  /**
   * Protobuf type {@code Goto}
   */
  public static final class Goto extends
      com.google.protobuf.GeneratedMessage
      implements GotoOrBuilder {
    // Use Goto.newBuilder() to construct.
    private Goto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Goto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Goto defaultInstance;
    public static Goto getDefaultInstance() {
      return defaultInstance;
    }

    public Goto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Goto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uavId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              x_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              y_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              z_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              yaw_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_Goto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_Goto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.URS_WearableProto.Goto.class, com.tutorial.protobuf.URS_WearableProto.Goto.Builder.class);
    }

    public static com.google.protobuf.Parser<Goto> PARSER =
        new com.google.protobuf.AbstractParser<Goto>() {
      public Goto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Goto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Goto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 uav_id = 1;
    public static final int UAV_ID_FIELD_NUMBER = 1;
    private int uavId_;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public boolean hasUavId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public int getUavId() {
      return uavId_;
    }

    // optional double x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>optional double x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    // optional double y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private double y_;
    /**
     * <code>optional double y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double y = 3;</code>
     */
    public double getY() {
      return y_;
    }

    // optional double z = 4;
    public static final int Z_FIELD_NUMBER = 4;
    private double z_;
    /**
     * <code>optional double z = 4;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double z = 4;</code>
     */
    public double getZ() {
      return z_;
    }

    // optional double yaw = 5;
    public static final int YAW_FIELD_NUMBER = 5;
    private double yaw_;
    /**
     * <code>optional double yaw = 5;</code>
     */
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double yaw = 5;</code>
     */
    public double getYaw() {
      return yaw_;
    }

    private void initFields() {
      uavId_ = 0;
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
      yaw_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uavId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, yaw_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uavId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, yaw_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.Goto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tutorial.protobuf.URS_WearableProto.Goto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Goto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tutorial.protobuf.URS_WearableProto.GotoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_Goto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_Goto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.URS_WearableProto.Goto.class, com.tutorial.protobuf.URS_WearableProto.Goto.Builder.class);
      }

      // Construct using com.tutorial.protobuf.URS_WearableProto.Goto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uavId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        yaw_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_Goto_descriptor;
      }

      public com.tutorial.protobuf.URS_WearableProto.Goto getDefaultInstanceForType() {
        return com.tutorial.protobuf.URS_WearableProto.Goto.getDefaultInstance();
      }

      public com.tutorial.protobuf.URS_WearableProto.Goto build() {
        com.tutorial.protobuf.URS_WearableProto.Goto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.URS_WearableProto.Goto buildPartial() {
        com.tutorial.protobuf.URS_WearableProto.Goto result = new com.tutorial.protobuf.URS_WearableProto.Goto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uavId_ = uavId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.yaw_ = yaw_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.URS_WearableProto.Goto) {
          return mergeFrom((com.tutorial.protobuf.URS_WearableProto.Goto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.URS_WearableProto.Goto other) {
        if (other == com.tutorial.protobuf.URS_WearableProto.Goto.getDefaultInstance()) return this;
        if (other.hasUavId()) {
          setUavId(other.getUavId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.URS_WearableProto.Goto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.URS_WearableProto.Goto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 uav_id = 1;
      private int uavId_ ;
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public boolean hasUavId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public int getUavId() {
        return uavId_;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder setUavId(int value) {
        bitField0_ |= 0x00000001;
        uavId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder clearUavId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uavId_ = 0;
        onChanged();
        return this;
      }

      // optional double x = 2;
      private double x_ ;
      /**
       * <code>optional double x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      // optional double y = 3;
      private double y_ ;
      /**
       * <code>optional double y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      // optional double z = 4;
      private double z_ ;
      /**
       * <code>optional double z = 4;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public double getZ() {
        return z_;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder setZ(double value) {
        bitField0_ |= 0x00000008;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0D;
        onChanged();
        return this;
      }

      // optional double yaw = 5;
      private double yaw_ ;
      /**
       * <code>optional double yaw = 5;</code>
       */
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public double getYaw() {
        return yaw_;
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public Builder setYaw(double value) {
        bitField0_ |= 0x00000010;
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yaw_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Goto)
    }

    static {
      defaultInstance = new Goto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Goto)
  }

  public interface AtOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 uav_id = 1;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    boolean hasUavId();
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    int getUavId();

    // optional double x = 2;
    /**
     * <code>optional double x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 2;</code>
     */
    double getX();

    // optional double y = 3;
    /**
     * <code>optional double y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 3;</code>
     */
    double getY();

    // optional double z = 4;
    /**
     * <code>optional double z = 4;</code>
     */
    boolean hasZ();
    /**
     * <code>optional double z = 4;</code>
     */
    double getZ();

    // optional double yaw = 5;
    /**
     * <code>optional double yaw = 5;</code>
     */
    boolean hasYaw();
    /**
     * <code>optional double yaw = 5;</code>
     */
    double getYaw();
  }
  /**
   * Protobuf type {@code At}
   */
  public static final class At extends
      com.google.protobuf.GeneratedMessage
      implements AtOrBuilder {
    // Use At.newBuilder() to construct.
    private At(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private At(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final At defaultInstance;
    public static At getDefaultInstance() {
      return defaultInstance;
    }

    public At getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private At(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uavId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              x_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              y_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              z_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              yaw_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_At_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_At_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.URS_WearableProto.At.class, com.tutorial.protobuf.URS_WearableProto.At.Builder.class);
    }

    public static com.google.protobuf.Parser<At> PARSER =
        new com.google.protobuf.AbstractParser<At>() {
      public At parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new At(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<At> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 uav_id = 1;
    public static final int UAV_ID_FIELD_NUMBER = 1;
    private int uavId_;
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public boolean hasUavId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 uav_id = 1;</code>
     */
    public int getUavId() {
      return uavId_;
    }

    // optional double x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>optional double x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    // optional double y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private double y_;
    /**
     * <code>optional double y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double y = 3;</code>
     */
    public double getY() {
      return y_;
    }

    // optional double z = 4;
    public static final int Z_FIELD_NUMBER = 4;
    private double z_;
    /**
     * <code>optional double z = 4;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double z = 4;</code>
     */
    public double getZ() {
      return z_;
    }

    // optional double yaw = 5;
    public static final int YAW_FIELD_NUMBER = 5;
    private double yaw_;
    /**
     * <code>optional double yaw = 5;</code>
     */
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double yaw = 5;</code>
     */
    public double getYaw() {
      return yaw_;
    }

    private void initFields() {
      uavId_ = 0;
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
      yaw_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uavId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, yaw_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uavId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, z_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, yaw_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.At parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tutorial.protobuf.URS_WearableProto.At prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code At}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tutorial.protobuf.URS_WearableProto.AtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_At_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_At_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.URS_WearableProto.At.class, com.tutorial.protobuf.URS_WearableProto.At.Builder.class);
      }

      // Construct using com.tutorial.protobuf.URS_WearableProto.At.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uavId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        yaw_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_At_descriptor;
      }

      public com.tutorial.protobuf.URS_WearableProto.At getDefaultInstanceForType() {
        return com.tutorial.protobuf.URS_WearableProto.At.getDefaultInstance();
      }

      public com.tutorial.protobuf.URS_WearableProto.At build() {
        com.tutorial.protobuf.URS_WearableProto.At result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.URS_WearableProto.At buildPartial() {
        com.tutorial.protobuf.URS_WearableProto.At result = new com.tutorial.protobuf.URS_WearableProto.At(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uavId_ = uavId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.yaw_ = yaw_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.URS_WearableProto.At) {
          return mergeFrom((com.tutorial.protobuf.URS_WearableProto.At)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.URS_WearableProto.At other) {
        if (other == com.tutorial.protobuf.URS_WearableProto.At.getDefaultInstance()) return this;
        if (other.hasUavId()) {
          setUavId(other.getUavId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.URS_WearableProto.At parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.URS_WearableProto.At) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 uav_id = 1;
      private int uavId_ ;
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public boolean hasUavId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public int getUavId() {
        return uavId_;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder setUavId(int value) {
        bitField0_ |= 0x00000001;
        uavId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uav_id = 1;</code>
       */
      public Builder clearUavId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uavId_ = 0;
        onChanged();
        return this;
      }

      // optional double x = 2;
      private double x_ ;
      /**
       * <code>optional double x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      // optional double y = 3;
      private double y_ ;
      /**
       * <code>optional double y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      // optional double z = 4;
      private double z_ ;
      /**
       * <code>optional double z = 4;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public double getZ() {
        return z_;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder setZ(double value) {
        bitField0_ |= 0x00000008;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double z = 4;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0D;
        onChanged();
        return this;
      }

      // optional double yaw = 5;
      private double yaw_ ;
      /**
       * <code>optional double yaw = 5;</code>
       */
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public double getYaw() {
        return yaw_;
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public Builder setYaw(double value) {
        bitField0_ |= 0x00000010;
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double yaw = 5;</code>
       */
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yaw_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:At)
    }

    static {
      defaultInstance = new At(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:At)
  }

  public interface missionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string start = 1;
    /**
     * <code>optional string start = 1;</code>
     */
    boolean hasStart();
    /**
     * <code>optional string start = 1;</code>
     */
    java.lang.String getStart();
    /**
     * <code>optional string start = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartBytes();

    // optional string pause = 2;
    /**
     * <code>optional string pause = 2;</code>
     */
    boolean hasPause();
    /**
     * <code>optional string pause = 2;</code>
     */
    java.lang.String getPause();
    /**
     * <code>optional string pause = 2;</code>
     */
    com.google.protobuf.ByteString
        getPauseBytes();

    // optional string reset = 3;
    /**
     * <code>optional string reset = 3;</code>
     */
    boolean hasReset();
    /**
     * <code>optional string reset = 3;</code>
     */
    java.lang.String getReset();
    /**
     * <code>optional string reset = 3;</code>
     */
    com.google.protobuf.ByteString
        getResetBytes();
  }
  /**
   * Protobuf type {@code mission}
   */
  public static final class mission extends
      com.google.protobuf.GeneratedMessage
      implements missionOrBuilder {
    // Use mission.newBuilder() to construct.
    private mission(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private mission(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final mission defaultInstance;
    public static mission getDefaultInstance() {
      return defaultInstance;
    }

    public mission getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private mission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              start_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pause_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reset_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_mission_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorial.protobuf.URS_WearableProto.internal_static_mission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorial.protobuf.URS_WearableProto.mission.class, com.tutorial.protobuf.URS_WearableProto.mission.Builder.class);
    }

    public static com.google.protobuf.Parser<mission> PARSER =
        new com.google.protobuf.AbstractParser<mission>() {
      public mission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new mission(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<mission> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string start = 1;
    public static final int START_FIELD_NUMBER = 1;
    private java.lang.Object start_;
    /**
     * <code>optional string start = 1;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string start = 1;</code>
     */
    public java.lang.String getStart() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          start_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string start = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartBytes() {
      java.lang.Object ref = start_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        start_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pause = 2;
    public static final int PAUSE_FIELD_NUMBER = 2;
    private java.lang.Object pause_;
    /**
     * <code>optional string pause = 2;</code>
     */
    public boolean hasPause() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string pause = 2;</code>
     */
    public java.lang.String getPause() {
      java.lang.Object ref = pause_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pause_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pause = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPauseBytes() {
      java.lang.Object ref = pause_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string reset = 3;
    public static final int RESET_FIELD_NUMBER = 3;
    private java.lang.Object reset_;
    /**
     * <code>optional string reset = 3;</code>
     */
    public boolean hasReset() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string reset = 3;</code>
     */
    public java.lang.String getReset() {
      java.lang.Object ref = reset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reset_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reset = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResetBytes() {
      java.lang.Object ref = reset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      start_ = "";
      pause_ = "";
      reset_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStartBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPauseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResetBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStartBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPauseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResetBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tutorial.protobuf.URS_WearableProto.mission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tutorial.protobuf.URS_WearableProto.mission prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tutorial.protobuf.URS_WearableProto.missionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_mission_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_mission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorial.protobuf.URS_WearableProto.mission.class, com.tutorial.protobuf.URS_WearableProto.mission.Builder.class);
      }

      // Construct using com.tutorial.protobuf.URS_WearableProto.mission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        start_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pause_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        reset_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorial.protobuf.URS_WearableProto.internal_static_mission_descriptor;
      }

      public com.tutorial.protobuf.URS_WearableProto.mission getDefaultInstanceForType() {
        return com.tutorial.protobuf.URS_WearableProto.mission.getDefaultInstance();
      }

      public com.tutorial.protobuf.URS_WearableProto.mission build() {
        com.tutorial.protobuf.URS_WearableProto.mission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tutorial.protobuf.URS_WearableProto.mission buildPartial() {
        com.tutorial.protobuf.URS_WearableProto.mission result = new com.tutorial.protobuf.URS_WearableProto.mission(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pause_ = pause_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reset_ = reset_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorial.protobuf.URS_WearableProto.mission) {
          return mergeFrom((com.tutorial.protobuf.URS_WearableProto.mission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorial.protobuf.URS_WearableProto.mission other) {
        if (other == com.tutorial.protobuf.URS_WearableProto.mission.getDefaultInstance()) return this;
        if (other.hasStart()) {
          bitField0_ |= 0x00000001;
          start_ = other.start_;
          onChanged();
        }
        if (other.hasPause()) {
          bitField0_ |= 0x00000002;
          pause_ = other.pause_;
          onChanged();
        }
        if (other.hasReset()) {
          bitField0_ |= 0x00000004;
          reset_ = other.reset_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorial.protobuf.URS_WearableProto.mission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorial.protobuf.URS_WearableProto.mission) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string start = 1;
      private java.lang.Object start_ = "";
      /**
       * <code>optional string start = 1;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string start = 1;</code>
       */
      public java.lang.String getStart() {
        java.lang.Object ref = start_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          start_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string start = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartBytes() {
        java.lang.Object ref = start_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          start_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string start = 1;</code>
       */
      public Builder setStart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string start = 1;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = getDefaultInstance().getStart();
        onChanged();
        return this;
      }
      /**
       * <code>optional string start = 1;</code>
       */
      public Builder setStartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        start_ = value;
        onChanged();
        return this;
      }

      // optional string pause = 2;
      private java.lang.Object pause_ = "";
      /**
       * <code>optional string pause = 2;</code>
       */
      public boolean hasPause() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string pause = 2;</code>
       */
      public java.lang.String getPause() {
        java.lang.Object ref = pause_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pause_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pause = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPauseBytes() {
        java.lang.Object ref = pause_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pause = 2;</code>
       */
      public Builder setPause(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pause_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pause = 2;</code>
       */
      public Builder clearPause() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pause_ = getDefaultInstance().getPause();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pause = 2;</code>
       */
      public Builder setPauseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pause_ = value;
        onChanged();
        return this;
      }

      // optional string reset = 3;
      private java.lang.Object reset_ = "";
      /**
       * <code>optional string reset = 3;</code>
       */
      public boolean hasReset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string reset = 3;</code>
       */
      public java.lang.String getReset() {
        java.lang.Object ref = reset_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reset_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reset = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResetBytes() {
        java.lang.Object ref = reset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reset = 3;</code>
       */
      public Builder setReset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reset = 3;</code>
       */
      public Builder clearReset() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reset_ = getDefaultInstance().getReset();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reset = 3;</code>
       */
      public Builder setResetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reset_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mission)
    }

    static {
      defaultInstance = new mission(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mission)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_drone_id_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_drone_id_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Goto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Goto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_At_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_At_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mission_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022URS_Wearable.proto\"\032\n\010drone_id\022\016\n\006uav_" +
      "id\030\001 \001(\005\"D\n\004Goto\022\016\n\006uav_id\030\001 \001(\005\022\t\n\001x\030\002 " +
      "\001(\001\022\t\n\001y\030\003 \001(\001\022\t\n\001z\030\004 \001(\001\022\013\n\003yaw\030\005 \001(\001\"B" +
      "\n\002At\022\016\n\006uav_id\030\001 \001(\005\022\t\n\001x\030\002 \001(\001\022\t\n\001y\030\003 \001" +
      "(\001\022\t\n\001z\030\004 \001(\001\022\013\n\003yaw\030\005 \001(\001\"6\n\007mission\022\r\n" +
      "\005start\030\001 \001(\t\022\r\n\005pause\030\002 \001(\t\022\r\n\005reset\030\003 \001" +
      "(\tB*\n\025com.tutorial.protobufB\021URS_Wearabl" +
      "eProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_drone_id_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_drone_id_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_drone_id_descriptor,
              new java.lang.String[] { "UavId", });
          internal_static_Goto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Goto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Goto_descriptor,
              new java.lang.String[] { "UavId", "X", "Y", "Z", "Yaw", });
          internal_static_At_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_At_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_At_descriptor,
              new java.lang.String[] { "UavId", "X", "Y", "Z", "Yaw", });
          internal_static_mission_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_mission_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mission_descriptor,
              new java.lang.String[] { "Start", "Pause", "Reset", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
